<?php

/**
 * BaseSystemSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property boolean $fast_user_register
 * @property boolean $fast_team_create
 * @property boolean $email_team_create
 * @property boolean $email_game_create
 * 
 * @method integer        getId()                      Returns the current record's "id" value
 * @method boolean        getFastUserRegister()        Returns the current record's "fast_user_register" value
 * @method boolean        getFastTeamCreate()          Returns the current record's "fast_team_create" value
 * @method boolean        getEmailTeamCreate()         Returns the current record's "email_team_create" value
 * @method boolean        getEmailGameCreate()         Returns the current record's "email_game_create" value
 * @method SystemSettings setId()                      Sets the current record's "id" value
 * @method SystemSettings setFastUserRegister()        Sets the current record's "fast_user_register" value
 * @method SystemSettings setFastTeamCreate()          Sets the current record's "fast_team_create" value
 * @method SystemSettings setEmailTeamCreate()         Sets the current record's "email_team_create" value
 * @method SystemSettings setEmailGameCreate()         Sets the current record's "email_game_create" value
 * 
 * @package    sf
 * @subpackage model
 * @author     VozdvIN
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSystemSettings extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('system_settings');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('fast_user_register', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('fast_team_create', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('email_team_create', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('email_game_create', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}