pollSuccess:
  has_layout: false

autoUpdateSuccess:
  metas:
    title: "Автопересчет игры"

reportSuccess:
  metas:
    title: "Результаты игры"
  has_layout: true

all:
  metas:
    title: "Управление игрой"
  has_layout: true