# Системные настройки, запись существует в одном экземпляре
SystemSettings:
  tableName: system_settings
  columns:
    id: { type: integer, primary: true, notnull: true }
    # Число дней до игры, когда открывается анонс
    games_announce_interval: { type: integer, notnull: true, default: 31 }
    # Разрешить мгновенную регистрацию пользователей
    fast_user_register: { type: boolean, notnull: true, default: false }
    # Разрешить быстрое создание команд (без модерирования или подтверждения по почте)
    fast_team_create: { type: boolean, notnull: true, default: false }
    # Разрешить создание команд через почту
    email_team_create: { type: boolean, notnull: true, default: true }
    # Разрешить создание игр через почту
    email_game_create: { type: boolean, notnull: true, default: false }